[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Copyright (C) WD Studios L.L.C. All Rights Reserved. <a class="text-muted" href="https://gethyas.com/"></a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">A New version of APUI has Released!</a>'

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
    footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Aperture UI</a>'
    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Aperture UI</a>'

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20
  [nl.params]
    languageISO = "NL"
    languageTag = "nl-NL"
    titleAddition = "Modern documentatie-thema"
    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
    titleHome = "Doks thema"
    footer = 'Mogelijk gemaakt door <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, en <a href="https://getdoks.org/">Doks</a>'
    alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'
